package:
  name: menpowidgets
  version: {{ environ['CONDACI_VERSION'] }}

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - menpo 0.6.*
    - ipython 4.*
    - jupyter 1.*
    - ipywidgets >=4.1.1,<5.0
    - traitlets >=4.1,<5.0

test:
  imports:
  - menpowidgets

about:
  home: https://github.com/menpo/menpowidgets/
  license: BSD
